import {
  User,
  Listing,
  Task,
  Commission,
  Inquiry,
  Reservation,
  CustomOrder,
  City,
} from "./types";

export const cities: City[] = [
  { id: "c1", name: "Kano Municipal", state: "Kano", listingCount: 12, agentCount: 6 },
  { id: "c2", name: "Fagge", state: "Kano", listingCount: 8, agentCount: 4 },
  { id: "c3", name: "Tarauni", state: "Kano", listingCount: 6, agentCount: 3 },
  { id: "c4", name: "Nassarawa", state: "Kano", listingCount: 9, agentCount: 5 },
];

export const users: User[] = [
  {
    id: "u1", name: "Sani Abubakar", email: "sani@propease.ng",
    role: "head", city: "Kano Municipal", walletBalance: 0,
  },
  {
    id: "u2", name: "Aisha Bello", email: "aisha@propease.ng",
    role: "ambassador", city: "Kano Municipal", walletBalance: 245000,
    canCreateTasks: true,
  },
  {
    id: "u3", name: "Musa Ibrahim", email: "musa@propease.ng",
    role: "ambassador", city: "Fagge", walletBalance: 182000,
    canCreateTasks: false,
  },
  {
    id: "u4", name: "Fatima Usman", email: "fatima@propease.ng",
    role: "agent", city: "Kano Municipal", walletBalance: 89000,
    ambassadorId: "u2",
  },
  {
    id: "u5", name: "Zainab Adamu", email: "zainab@propease.ng",
    role: "agent", city: "Kano Municipal", walletBalance: 62000,
    ambassadorId: "u2",
    canCloseDeals: true,
  },
  {
    id: "u6", name: "Ahmad Suleiman", email: "ahmad@propease.ng",
    role: "agent", city: "Fagge", walletBalance: 45000,
    ambassadorId: "u3",
  },
  {
    id: "u7", name: "Halima Garba", email: "halima@propease.ng",
    role: "agent", city: "Fagge", walletBalance: 31000,
    ambassadorId: "u3",
  },
];

export const listings: Listing[] = [
  {
    id: "l1",
    title: "4-Bedroom Duplex — Kano Municipal",
    description:
      "A spacious 4-bedroom duplex in the heart of Kano Municipal. Features include modern kitchen, tiled floors throughout, borehole water supply, and 24/7 security. Walking distance to Kano Line bus terminal and major markets.",
    propertyType: "house",
    listingType: "rent",
    rentTier: "full",
    annualRent: 1_800_000,
    damageDeposit: 200_000,
    maintenanceCharge: 100_000,
    status: "available",
    category: "portfolio",
    photos: [
      { id: "p1", url: "/images/house1-1.jpg", alt: "Front view" },
      { id: "p2", url: "/images/house1-2.jpg", alt: "Living room" },
      { id: "p3", url: "/images/house1-3.jpg", alt: "Kitchen" },
    ],
    lat: 12.0010,
    lng: 8.5245,
    address: "No. 15 Sultan Road, Kano Municipal",
    city: "Kano Municipal",
    postedBy: users[0],
    assignedAgent: users[3],
    createdAt: "2026-05-15",
    bedrooms: 4,
    bathrooms: 4,
    sqft: 2800,
    features: ["Borehole", "24/7 Security", "Parking", "Generator"],
    price: 1800000,
    priceLabel: "₦1,800,000/yr",
  },
  {
    id: "l2",
    title: "3-Bedroom Flat — Fagge",
    description:
      "Well-maintained 3-bedroom flat in Fagge LGA. Close to Murtala Muhammad Library and Fagge market. Enjoy a quiet neighborhood with access to main roads and public transport.",
    propertyType: "flat",
    listingType: "rent",
    rentTier: "damages",
    annualRent: 1_200_000,
    damageDeposit: 150_000,
    status: "available",
    category: "portfolio",
    photos: [
      { id: "p4", url: "/images/flat1-1.jpg", alt: "Exterior" },
      { id: "p5", url: "/images/flat1-2.jpg", alt: "Bedroom" },
    ],
    lat: 11.9930,
    lng: 8.5350,
    address: "Block C, Aminu Kano Crescent, Fagge",
    city: "Fagge",
    postedBy: users[0],
    assignedAgent: users[5],
    createdAt: "2026-05-20",
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1500,
    price: 1200000,
    priceLabel: "₦1,200,000/yr",
  },
  {
    id: "l3",
    title: "Commercial Plaza — Fagge",
    description:
      "Prime commercial space in the bustling Fagge area. Ground floor shop with upper level office space. High foot traffic area near Kano's main transport interchange. Suitable for retail, restaurant, or office.",
    propertyType: "commercial",
    listingType: "rent",
    rentTier: "normal",
    annualRent: 3_500_000,
    status: "available",
    category: "partnership",
    partnerCompany: "Alheri Properties Ltd",
    photos: [
      { id: "p6", url: "/images/commercial1-1.jpg", alt: "Front view" },
    ],
    lat: 11.9945,
    lng: 8.5370,
    address: "No. 5 Fagge Market Road, Fagge",
    city: "Fagge",
    postedBy: users[0],
    createdAt: "2026-05-10",
    sqft: 2200,
    price: 3500000,
    priceLabel: "₦3,500,000/yr",
  },
  {
    id: "l4",
    title: "Land Plot — Tarauni",
    description:
      "500sqm plot of land in the developing Tarauni area. Perfect for residential construction. Close to Bayero University Kano and new housing estates. Documented with C of O.",
    propertyType: "land",
    listingType: "sale",
    salePrice: 8_500_000,
    status: "available",
    category: "portfolio",
    photos: [
      { id: "p7", url: "/images/land1-1.jpg", alt: "Plot view" },
    ],
    lat: 11.9750,
    lng: 8.5450,
    address: "Tarauni Extension Layout, Tarauni",
    city: "Tarauni",
    postedBy: users[1],
    createdAt: "2026-05-08",
    sqft: 500,
    price: 8500000,
    priceLabel: "₦8,500,000",
  },
  {
    id: "l5",
    title: "Luxury 5-Bedroom Villa — Nassarawa",
    description:
      "Premium luxury villa in the exclusive Nassarawa GRA. Italian marble flooring, central AC, private swimming pool, and landscaped garden. Staff quarters and 3-car garage included.",
    propertyType: "house",
    listingType: "rent",
    rentTier: "full",
    annualRent: 5_000_000,
    damageDeposit: 500_000,
    maintenanceCharge: 250_000,
    status: "available",
    category: "portfolio",
    photos: [
      { id: "p8", url: "/images/house2-1.jpg", alt: "Exterior" },
      { id: "p9", url: "/images/house2-2.jpg", alt: "Pool" },
      { id: "p10", url: "/images/house2-3.jpg", alt: "Living room" },
    ],
    lat: 11.9830,
    lng: 8.5120,
    address: "No. 8 GRA Road, Nassarawa",
    city: "Nassarawa",
    postedBy: users[2],
    createdAt: "2026-05-18",
    bedrooms: 5,
    bathrooms: 5,
    sqft: 4500,
    features: ["Swimming Pool", "Central AC", "Staff Quarters", "Garden"],
    price: 5000000,
    priceLabel: "₦5,000,000/yr",
  },
  {
    id: "l6",
    title: "2-Bedroom Self-Contain — Kano Municipal",
    description:
      "Affordable 2-bedroom self-contained apartment in Kano Municipal. Ideal for young professionals or small families. Tiled floors, modern bathroom, and kitchenette.",
    propertyType: "flat",
    listingType: "rent",
    rentTier: "damages",
    annualRent: 600_000,
    damageDeposit: 80_000,
    status: "reserved",
    category: "portfolio",
    photos: [
      { id: "p11", url: "/images/flat2-1.jpg", alt: "Living area" },
    ],
    lat: 12.0080,
    lng: 8.5300,
    address: "No. 22 Kabuga Road, Kano Municipal",
    city: "Kano Municipal",
    postedBy: users[1],
    assignedAgent: users[4],
    createdAt: "2026-05-12",
    bedrooms: 2,
    bathrooms: 1,
    sqft: 800,
    price: 600000,
    priceLabel: "₦600,000/yr",
  },
  {
    id: "l7",
    title: "3-Bedroom House — Nassarawa",
    description:
      "Recently renovated 3-bedroom house in the quiet Nassarawa area. Good road network, reliable electricity from PHCN, and close to schools and hospitals.",
    propertyType: "house",
    listingType: "sale",
    salePrice: 25_000_000,
    status: "available",
    category: "partnership",
    partnerCompany: "Gidan Masa Realty",
    photos: [
      { id: "p12", url: "/images/house3-1.jpg", alt: "Front view" },
      { id: "p13", url: "/images/house3-2.jpg", alt: "Kitchen" },
    ],
    lat: 11.9880,
    lng: 8.5180,
    address: "No. 45 Ibrahim Taiwo Road, Nassarawa",
    city: "Nassarawa",
    postedBy: users[0],
    createdAt: "2026-05-22",
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1800,
    price: 25000000,
    priceLabel: "₦25,000,000",
  },
  {
    id: "l8",
    title: "Land Plot — Kano Municipal",
    description:
      "Prime 300sqm land plot in Kano Municipal near the Government House. All documents intact. Perfect for commercial development or high-end residential.",
    propertyType: "land",
    listingType: "sale",
    salePrice: 12_000_000,
    status: "available",
    category: "portfolio",
    photos: [
      { id: "p14", url: "/images/land2-1.jpg", alt: "Land view" },
    ],
    lat: 12.0040,
    lng: 8.5200,
    address: "Race Course Area, Kano Municipal",
    city: "Kano Municipal",
    postedBy: users[1],
    assignedAgent: users[3],
    createdAt: "2026-04-28",
    sqft: 300,
    price: 12000000,
    priceLabel: "₦12,000,000",
  },
  {
    id: "l9",
    title: "1-Bedroom Flat — Tarauni",
    description:
      "Cozy 1-bedroom flat in a new development in Tarauni. Suitable for students or single professionals. Close to BUK, Ahmadu Bello Way, and local amenities.",
    propertyType: "flat",
    listingType: "rent",
    rentTier: "normal",
    annualRent: 350_000,
    status: "available",
    category: "portfolio",
    photos: [
      { id: "p15", url: "/images/flat3-1.jpg", alt: "Flat exterior" },
    ],
    lat: 11.9720,
    lng: 8.5480,
    address: "No. 7 BUK Road, Tarauni",
    city: "Tarauni",
    postedBy: users[1],
    createdAt: "2026-05-25",
    bedrooms: 1,
    bathrooms: 1,
    sqft: 500,
    price: 350000,
    priceLabel: "₦350,000/yr",
  },
  {
    id: "l10",
    title: "Warehouse Space — Fagge",
    description:
      "Large warehouse space available for rent in the industrial area of Fagge. Ideal for storage, manufacturing, or logistics operations. 24/7 security and truck access.",
    propertyType: "commercial",
    listingType: "rent",
    rentTier: "damages",
    annualRent: 2_400_000,
    damageDeposit: 300_000,
    status: "taken",
    category: "portfolio",
    photos: [
      { id: "p16", url: "/images/warehouse1-1.jpg", alt: "Warehouse interior" },
    ],
    lat: 11.9910,
    lng: 8.5400,
    address: "Industrial Layout, Fagge",
    city: "Fagge",
    postedBy: users[2],
    createdAt: "2026-04-15",
    sqft: 5000,
    price: 2400000,
    priceLabel: "₦2,400,000/yr",
  },
];

export const tasks: Task[] = [
  {
    id: "t1",
    title: "Find 3-bedroom house in Kano Municipal",
    description: "Client is looking for a 3-bedroom house for rent in Kano Municipal area. Budget up to ₦1.5M per year. Preferably with generator and borehole.",
    propertyType: "house",
    area: "Kano Municipal",
    budget: 1_500_000,
    deadline: "2026-06-15",
    notes: "Client prefers a quiet neighborhood. Children in the family so need good school proximity.",
    createdBy: users[1],
    assignedTo: users[3],
    status: "in_progress",
    source: "internal",
    comments: [
      {
        id: "tc1",
        author: users[3],
        text: "I've checked 3 houses so far. One looks promising on Ibrahim Taiwo Road. Sending details tomorrow.",
        createdAt: "2026-05-26",
      },
      {
        id: "tc2",
        author: users[1],
        text: "Good. Send photos and I'll share with the client.",
        createdAt: "2026-05-27",
      },
    ],
    createdAt: "2026-05-20",
  },
  {
    id: "t2",
    title: "Land plot for client in Tarauni",
    description: "Client wants to buy land in Tarauni for residential construction. Needs C of O. Budget ₦5M - ₦7M.",
    propertyType: "land",
    area: "Tarauni",
    budget: 7_000_000,
    deadline: "2026-06-30",
    notes: "Client wants to build a 4-bedroom house. Needs plot that's not waterlogged.",
    createdBy: users[1],
    assignedTo: users[4],
    status: "open",
    source: "client_request",
    comments: [],
    createdAt: "2026-05-25",
  },
  {
    id: "t3",
    title: "Commercial space in Fagge for new restaurant",
    description: "Looking for ground floor commercial space with kitchen hookup in Fagge. High foot traffic area preferred.",
    propertyType: "commercial",
    area: "Fagge",
    budget: 2_000_000,
    deadline: "2026-06-10",
    notes: "Need to be close to major road. Minimum 200sqm.",
    createdBy: users[0],
    assignedTo: users[6],
    status: "open",
    source: "internal",
    comments: [],
    createdAt: "2026-05-28",
  },
  {
    id: "t4",
    title: "1-bedroom flat near BUK for student",
    description: "A student at Bayero University needs a 1-bedroom flat within walking distance of the main campus. Budget ₦300K-₦400K per year.",
    propertyType: "flat",
    area: "Tarauni",
    budget: 400_000,
    deadline: "2026-06-05",
    notes: "Must be close to BUK gate. Preferably in a safe compound.",
    createdBy: users[2],
    assignedTo: users[6],
    status: "fulfilled",
    source: "client_request",
    submittedListingId: "l9",
    comments: [
      {
        id: "tc3",
        author: users[6],
        text: "Found a good option on BUK Road. Flat #9 just became available. Sending details.",
        createdAt: "2026-05-29",
      },
    ],
    createdAt: "2026-05-22",
  },
  {
    id: "t5",
    title: "Luxury villa search for VIP client",
    description: "Corporate client relocating to Kano needs a luxury 4-5 bedroom villa in Nassarawa GRA. Budget up to ₦6M/yr. Must have pool and staff quarters.",
    propertyType: "house",
    area: "Nassarawa",
    budget: 6_000_000,
    deadline: "2026-07-01",
    notes: "Very important client. Must be premium finish. International school proximity needed.",
    createdBy: users[0],
    assignedTo: users[5],
    status: "in_progress",
    source: "internal",
    comments: [
      {
        id: "tc4",
        author: users[5],
        text: "I've been in touch with agents in Nassarawa. The villa at #8 GRA Road is available. Requesting a viewing this week.",
        createdAt: "2026-05-27",
      },
    ],
    createdAt: "2026-05-24",
  },
];

export const commissions: Commission[] = [
  {
    id: "cm1",
    dealId: "d1",
    dealTitle: "Warehouse Space — Fagge (Taken)",
    dealType: "rent (full package)",
    totalAmount: 2_400_000,
    ambassadorRate: 0.08,
    ambassadorCut: 192_000,
    agentRate: 0.05,
    agentCut: 120_000,
    companyCut: 2_088_000,
    ambassador: users[2],
    agent: users[5],
    paidAt: "2026-04-20",
  },
];

export const inquiries: Inquiry[] = [
  {
    id: "iq1",
    listingId: "l1",
    listingTitle: "4-Bedroom Duplex — Kano Municipal",
    clientName: "Dr. Amina Yusuf",
    clientContact: "0803 123 4567",
    message: "Is this property still available? I am a medical doctor relocating from Abuja. Would like to schedule a viewing this weekend.",
    assignedAgent: users[3],
    status: "new",
    createdAt: "2026-05-28",
  },
  {
    id: "iq2",
    listingId: "l5",
    listingTitle: "Luxury 5-Bedroom Villa — Nassarawa",
    clientName: "Alh. Kabir Danjuma",
    clientContact: "0805 987 6543",
    message: "I am interested in this property. Please send more photos and details about the maintenance package.",
    assignedAgent: users[5],
    status: "read",
    createdAt: "2026-05-26",
  },
];

export const reservations: Reservation[] = [
  {
    id: "r1",
    listingId: "l6",
    listingTitle: "2-Bedroom Self-Contain — Kano Municipal",
    clientName: "Malam Nura Isah",
    holdingDeposit: 50_000,
    status: "pending",
    expiresAt: "2026-05-31",
    createdAt: "2026-05-28",
  },
];

export const customOrders: CustomOrder[] = [
  {
    id: "co1",
    propertyType: "house",
    area: "Nassarawa",
    budget: 3_000_000,
    notes: "Looking for a 4-bedroom house for rent. Must have borehole and be in a gated community.",
    clientName: "Hajiya Hauwa Sani",
    clientContact: "0701 234 5678",
    status: "routed",
    createdAt: "2026-05-27",
  },
];

export const platformStats = {
  totalUsers: 7,
  totalListings: 10,
  availableListings: 8,
  reservedListings: 1,
  takenListings: 1,
  totalTasks: 5,
  openTasks: 2,
  inProgressTasks: 2,
  fulfilledTasks: 1,
  totalCommissionsPaid: 312_000,
  totalRevenue: 2_088_000,
  totalWithdrawalsPending: 0,
};
