import {
  User, Listing, Task, Commission, Inquiry,
  Reservation, CustomOrder, City,
} from "./types";

const U = {
  house: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=600&h=400&fit=crop",
  living: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=600&h=400&fit=crop",
  kitchen: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&h=400&fit=crop",
  bedroom: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=600&h=400&fit=crop",
  bathroom: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&h=400&fit=crop",
  land: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=600&h=400&fit=crop",
  commercial: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=600&h=400&fit=crop",
  luxury: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=600&h=400&fit=crop",
  flat: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600&h=400&fit=crop",
  interior: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600&h=400&fit=crop",
  warehouse: "https://images.unsplash.com/photo-1586528116311-ad60dd2c6e3c?w=600&h=400&fit=crop",
  office: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&h=400&fit=crop",
  pool: "https://images.unsplash.com/photo-1576013551627-0cc20b4e5c2e?w=600&h=400&fit=crop",
  garden: "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=600&h=400&fit=crop",
  dining: "https://images.unsplash.com/photo-1617806118233-18e1de247200?w=600&h=400&fit=crop",
  rooftop: "https://images.unsplash.com/photo-1623298317883-6b70254edf31?w=600&h=400&fit=crop",
  compound: "https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=600&h=400&fit=crop",
  shop: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=600&h=400&fit=crop",
  studio: "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=600&h=400&fit=crop",
  lobby: "https://images.unsplash.com/photo-1562778612-e1e0cda9915c?w=600&h=400&fit=crop",
};

export const cities: City[] = [
  { id: "c1", name: "Kano Municipal", state: "Kano", listingCount: 12, agentCount: 6 },
  { id: "c2", name: "Fagge", state: "Kano", listingCount: 8, agentCount: 4 },
  { id: "c3", name: "Tarauni", state: "Kano", listingCount: 6, agentCount: 3 },
  { id: "c4", name: "Nassarawa", state: "Kano", listingCount: 9, agentCount: 5 },
];

export const users: User[] = [
  { id: "u0", name: "Dr. Khalid Suleiman", email: "khalid@propease.ng", role: "admin", city: "Kano Municipal", walletBalance: 0 },
  { id: "u1", name: "Sani Abubakar", email: "sani@propease.ng", role: "head", city: "Kano Municipal", walletBalance: 0 },
  { id: "u2", name: "Aisha Bello", email: "aisha@propease.ng", role: "ambassador", city: "Kano Municipal", walletBalance: 245000, canCreateTasks: true },
  { id: "u3", name: "Musa Ibrahim", email: "musa@propease.ng", role: "ambassador", city: "Fagge", walletBalance: 182000, canCreateTasks: false },
  { id: "u4", name: "Fatima Usman", email: "fatima@propease.ng", role: "agent", city: "Kano Municipal", walletBalance: 89000, ambassadorId: "u2" },
  { id: "u5", name: "Zainab Adamu", email: "zainab@propease.ng", role: "agent", city: "Kano Municipal", walletBalance: 62000, ambassadorId: "u2", canCloseDeals: true },
  { id: "u6", name: "Ahmad Suleiman", email: "ahmad@propease.ng", role: "agent", city: "Fagge", walletBalance: 45000, ambassadorId: "u3" },
  { id: "u7", name: "Halima Garba", email: "halima@propease.ng", role: "agent", city: "Fagge", walletBalance: 31000, ambassadorId: "u3" },
  { id: "u8", name: "Nura Muhd", email: "nura@propease.ng", role: "agent", city: "Kano Municipal", walletBalance: 120000, ambassadorId: "u2", canCloseDeals: true },
  { id: "u9", name: "Maryam Yusuf", email: "maryam@propease.ng", role: "ambassador", city: "Tarauni", walletBalance: 310000, canCreateTasks: true },
  { id: "u10", name: "Bashir Umar", email: "bashir@propease.ng", role: "agent", city: "Tarauni", walletBalance: 78000, ambassadorId: "u9" },
];

export const listings: Listing[] = [
  {
    id: "l1", title: "4-Bedroom Duplex — Kano Municipal",
    description: "A spacious 4-bedroom duplex in the heart of Kano Municipal. Modern kitchen, tiled floors, borehole water supply, and 24/7 security. Walking distance to Kano Line bus terminal and major markets.",
    propertyType: "house", listingType: "rent", rentTier: "full",
    annualRent: 1_800_000, damageDeposit: 200_000, maintenanceCharge: 100_000,
    status: "available", category: "portfolio",
    photos: [{ id: "p1", url: U.house, alt: "Front view" }, { id: "p2", url: U.living, alt: "Living room" }, { id: "p3", url: U.kitchen, alt: "Kitchen" }],
    lat: 12.0010, lng: 8.5245, address: "No. 15 Sultan Road, Kano Municipal", city: "Kano Municipal",
    postedBy: users[1], assignedAgent: users[4], createdAt: "2026-05-15",
    bedrooms: 4, bathrooms: 4, sqft: 2800, features: ["Borehole", "24/7 Security", "Parking", "Generator"],
    price: 1800000, priceLabel: "₦1,800,000/yr",
  },
  {
    id: "l2", title: "3-Bedroom Flat — Fagge",
    description: "Well-maintained 3-bedroom flat in Fagge LGA. Close to Murtala Muhammad Library and Fagge market. Quiet neighborhood with access to main roads and public transport.",
    propertyType: "flat", listingType: "rent", rentTier: "damages",
    annualRent: 1_200_000, damageDeposit: 150_000,
    status: "available", category: "portfolio",
    photos: [{ id: "p4", url: U.flat, alt: "Exterior" }, { id: "p5", url: U.bedroom, alt: "Bedroom" }],
    lat: 11.9930, lng: 8.5350, address: "Block C, Aminu Kano Crescent, Fagge", city: "Fagge",
    postedBy: users[1], assignedAgent: users[6], createdAt: "2026-05-20",
    bedrooms: 3, bathrooms: 2, sqft: 1500, price: 1200000, priceLabel: "₦1,200,000/yr",
  },
  {
    id: "l3", title: "Commercial Plaza — Fagge",
    description: "Prime commercial space in the bustling Fagge area. Ground floor shop with upper level office space. High foot traffic area near Kano's main transport interchange.",
    propertyType: "commercial", listingType: "rent", rentTier: "normal",
    annualRent: 3_500_000,
    status: "available", category: "partnership", partnerCompany: "Alheri Properties Ltd",
    photos: [{ id: "p6", url: U.commercial, alt: "Front view" }],
    lat: 11.9945, lng: 8.5370, address: "No. 5 Fagge Market Road, Fagge", city: "Fagge",
    postedBy: users[1], createdAt: "2026-05-10", sqft: 2200, price: 3500000, priceLabel: "₦3,500,000/yr",
  },
  {
    id: "l4", title: "Land Plot — Tarauni",
    description: "500sqm plot of land in developing Tarauni area. Perfect for residential construction. Close to Bayero University Kano and new housing estates. C of O available.",
    propertyType: "land", listingType: "sale", salePrice: 8_500_000,
    status: "available", category: "portfolio",
    photos: [{ id: "p7", url: U.land, alt: "Plot view" }],
    lat: 11.9750, lng: 8.5450, address: "Tarauni Extension Layout, Tarauni", city: "Tarauni",
    postedBy: users[2], createdAt: "2026-05-08", sqft: 500, price: 8500000, priceLabel: "₦8,500,000",
  },
  {
    id: "l5", title: "Luxury 5-Bedroom Villa — Nassarawa",
    description: "Premium luxury villa in exclusive Nassarawa GRA. Italian marble flooring, central AC, private pool, and landscaped garden. Staff quarters and 3-car garage.",
    propertyType: "house", listingType: "rent", rentTier: "full",
    annualRent: 5_000_000, damageDeposit: 500_000, maintenanceCharge: 250_000,
    status: "available", category: "portfolio",
    photos: [{ id: "p8", url: U.luxury, alt: "Exterior" }, { id: "p9", url: U.pool, alt: "Pool" }, { id: "p10", url: U.living, alt: "Living room" }],
    lat: 11.9830, lng: 8.5120, address: "No. 8 GRA Road, Nassarawa", city: "Nassarawa",
    postedBy: users[3], createdAt: "2026-05-18",
    bedrooms: 5, bathrooms: 5, sqft: 4500, features: ["Swimming Pool", "Central AC", "Staff Quarters", "Garden"],
    price: 5000000, priceLabel: "₦5,000,000/yr",
  },
  {
    id: "l6", title: "2-Bedroom Self-Contain — Kano Municipal",
    description: "Affordable 2-bedroom self-contained apartment in Kano Municipal. Ideal for young professionals or small families. Tiled floors, modern bathroom, kitchenette.",
    propertyType: "flat", listingType: "rent", rentTier: "damages",
    annualRent: 600_000, damageDeposit: 80_000,
    status: "reserved", category: "portfolio",
    photos: [{ id: "p11", url: U.interior, alt: "Living area" }],
    lat: 12.0080, lng: 8.5300, address: "No. 22 Kabuga Road, Kano Municipal", city: "Kano Municipal",
    postedBy: users[2], assignedAgent: users[5], createdAt: "2026-05-12",
    bedrooms: 2, bathrooms: 1, sqft: 800, price: 600000, priceLabel: "₦600,000/yr",
  },
  {
    id: "l7", title: "3-Bedroom House — Nassarawa",
    description: "Recently renovated 3-bedroom house in quiet Nassarawa area. Good road network, reliable electricity, close to schools and hospitals.",
    propertyType: "house", listingType: "sale", salePrice: 25_000_000,
    status: "available", category: "partnership", partnerCompany: "Gidan Masa Realty",
    photos: [{ id: "p12", url: U.compound, alt: "Front view" }, { id: "p13", url: U.kitchen, alt: "Kitchen" }],
    lat: 11.9880, lng: 8.5180, address: "No. 45 Ibrahim Taiwo Road, Nassarawa", city: "Nassarawa",
    postedBy: users[1], createdAt: "2026-05-22",
    bedrooms: 3, bathrooms: 2, sqft: 1800, price: 25000000, priceLabel: "₦25,000,000",
  },
  {
    id: "l8", title: "Land Plot — Kano Municipal",
    description: "Prime 300sqm land plot near the Government House. All documents intact. Perfect for commercial development or high-end residential.",
    propertyType: "land", listingType: "sale", salePrice: 12_000_000,
    status: "available", category: "portfolio",
    photos: [{ id: "p14", url: U.land, alt: "Land view" }],
    lat: 12.0040, lng: 8.5200, address: "Race Course Area, Kano Municipal", city: "Kano Municipal",
    postedBy: users[2], assignedAgent: users[4], createdAt: "2026-04-28",
    sqft: 300, price: 12000000, priceLabel: "₦12,000,000",
  },
  {
    id: "l9", title: "1-Bedroom Flat — Tarauni",
    description: "Cozy 1-bedroom flat near Bayero University. Suitable for students or single professionals. Close to Ahmadu Bello Way and local amenities.",
    propertyType: "flat", listingType: "rent", rentTier: "normal",
    annualRent: 350_000,
    status: "available", category: "portfolio",
    photos: [{ id: "p15", url: U.studio, alt: "Flat interior" }],
    lat: 11.9720, lng: 8.5480, address: "No. 7 BUK Road, Tarauni", city: "Tarauni",
    postedBy: users[2], createdAt: "2026-05-25",
    bedrooms: 1, bathrooms: 1, sqft: 500, price: 350000, priceLabel: "₦350,000/yr",
  },
  {
    id: "l10", title: "Warehouse Space — Fagge",
    description: "Large warehouse in the industrial area of Fagge. Ideal for storage, manufacturing, or logistics. 24/7 security and truck access.",
    propertyType: "commercial", listingType: "rent", rentTier: "damages",
    annualRent: 2_400_000, damageDeposit: 300_000,
    status: "taken", category: "portfolio",
    photos: [{ id: "p16", url: U.warehouse, alt: "Warehouse interior" }],
    lat: 11.9910, lng: 8.5400, address: "Industrial Layout, Fagge", city: "Fagge",
    postedBy: users[3], createdAt: "2026-04-15", sqft: 5000, price: 2400000, priceLabel: "₦2,400,000/yr",
  },
  {
    id: "l11", title: "Modern 3-Bedroom Apartment — Kano Municipal",
    description: "Brand new 3-bedroom apartment in a gated compound. Pop ceiling, tiled floors, modern kitchen with cabinets, and dedicated parking space. 24hr security.",
    propertyType: "flat", listingType: "rent", rentTier: "full",
    annualRent: 1_500_000, damageDeposit: 150_000, maintenanceCharge: 75_000,
    status: "available", category: "portfolio",
    photos: [{ id: "p17", url: U.flat, alt: "Building" }, { id: "p18", url: U.interior, alt: "Living room" }, { id: "p19", url: U.dining, alt: "Dining" }],
    lat: 12.0120, lng: 8.5180, address: "No. 3 Bompai Road, Kano Municipal", city: "Kano Municipal",
    postedBy: users[9], assignedAgent: users[10], createdAt: "2026-05-26",
    bedrooms: 3, bathrooms: 2, sqft: 1400, features: ["Gated Compound", "Parking", "Generator Pre-wired"],
    price: 1500000, priceLabel: "₦1,500,000/yr",
  },
  {
    id: "l12", title: "Executive Office Suite — Fagge",
    description: "Fully furnished executive office suite in a prime Fagge location. Reception area, 3 private offices, meeting room, and kitchenette. Ideal for professional services firm.",
    propertyType: "commercial", listingType: "rent", rentTier: "normal",
    annualRent: 2_800_000,
    status: "available", category: "portfolio",
    photos: [{ id: "p20", url: U.office, alt: "Office" }, { id: "p21", url: U.lobby, alt: "Reception" }],
    lat: 11.9950, lng: 8.5320, address: "3rd Floor, Kano Plaza, Fagge", city: "Fagge",
    postedBy: users[1], createdAt: "2026-05-27", sqft: 1200, price: 2800000, priceLabel: "₦2,800,000/yr",
  },
  {
    id: "l13", title: "6-Bedroom Mansion — Nassarawa",
    description: "Magnificent 6-bedroom mansion in the heart of Nassarawa GRA. Two living rooms, cinema room, indoor gym, swimming pool, lush garden, and 4-car garage. Staff quarters included.",
    propertyType: "house", listingType: "rent", rentTier: "full",
    annualRent: 8_500_000, damageDeposit: 1_000_000, maintenanceCharge: 400_000,
    status: "available", category: "partnership", partnerCompany: "Gidan Masa Realty",
    photos: [{ id: "p22", url: U.luxury, alt: "Mansion" }, { id: "p23", url: U.pool, alt: "Pool" }, { id: "p24", url: U.garden, alt: "Garden" }],
    lat: 11.9850, lng: 8.5080, address: "No. 12 GRA Road, Nassarawa", city: "Nassarawa",
    postedBy: users[0], createdAt: "2026-05-28",
    bedrooms: 6, bathrooms: 6, sqft: 6500,
    features: ["Swimming Pool", "Cinema Room", "Gym", "Garden", "Staff Quarters", "4-Car Garage"],
    price: 8500000, priceLabel: "₦8,500,000/yr",
  },
  {
    id: "l14", title: "Land Plot — Tarauni Extension",
    description: "800sqm corner plot in the fast-developing Tarauni Extension. High elevation, good drainage. Perfect for commercial or mixed-use development. C of O available.",
    propertyType: "land", listingType: "sale", salePrice: 15_000_000,
    status: "available", category: "portfolio",
    photos: [{ id: "p25", url: U.land, alt: "Land view" }],
    lat: 11.9700, lng: 8.5500, address: "Tarauni Extension, Phase 2, Tarauni", city: "Tarauni",
    postedBy: users[9], createdAt: "2026-05-29", sqft: 800, price: 15000000, priceLabel: "₦15,000,000",
  },
  {
    id: "l15", title: "Shop Space — Kano Municipal",
    description: "Prime retail shop space on busy Ibrahim Taiwo Road. High foot traffic, visible signage, storage room included. Suitable for fashion, electronics, or food outlet.",
    propertyType: "commercial", listingType: "rent", rentTier: "damages",
    annualRent: 1_200_000, damageDeposit: 150_000,
    status: "available", category: "portfolio",
    photos: [{ id: "p26", url: U.shop, alt: "Shop front" }],
    lat: 12.0020, lng: 8.5220, address: "Shop 5, Ibrahim Taiwo Road, Kano Municipal", city: "Kano Municipal",
    postedBy: users[1], assignedAgent: users[8], createdAt: "2026-05-30",
    sqft: 400, price: 1200000, priceLabel: "₦1,200,000/yr",
  },
  {
    id: "l16", title: "4-Bedroom Terrace — Fagge New Layout",
    description: "Modern 4-bedroom terrace duplex in the new Fagge Layout. Rooftop terrace, modern finishes, central courtyard. Perfect for a growing family.",
    propertyType: "house", listingType: "rent", rentTier: "damages",
    annualRent: 2_200_000, damageDeposit: 300_000,
    status: "available", category: "portfolio",
    photos: [{ id: "p27", url: U.rooftop, alt: "Rooftop" }, { id: "p28", url: U.living, alt: "Living room" }],
    lat: 11.9900, lng: 8.5380, address: "Plot 7, Fagge New Layout, Fagge", city: "Fagge",
    postedBy: users[3], assignedAgent: users[6], createdAt: "2026-05-31",
    bedrooms: 4, bathrooms: 3, sqft: 2200, features: ["Rooftop Terrace", "Central Courtyard", "Parking"],
    price: 2200000, priceLabel: "₦2,200,000/yr",
  },
  {
    id: "l17", title: "Penthouse Apartment — Kano Municipal",
    description: "Luxurious penthouse on the top floor of Kano's tallest residential building. Panoramic city views, open-plan living, premium finishes, and private rooftop access.",
    propertyType: "flat", listingType: "rent", rentTier: "full",
    annualRent: 4_500_000, damageDeposit: 500_000, maintenanceCharge: 200_000,
    status: "available", category: "portfolio",
    photos: [{ id: "p29", url: U.rooftop, alt: "View" }, { id: "p30", url: U.interior, alt: "Interior" }, { id: "p31", url: U.dining, alt: "Dining area" }],
    lat: 12.0060, lng: 8.5260, address: "Penthouse, Kano Tower, Kano Municipal", city: "Kano Municipal",
    postedBy: users[0], createdAt: "2026-06-01",
    bedrooms: 3, bathrooms: 3, sqft: 2500, features: ["Panoramic View", "Private Rooftop", "Central AC", "Concierge"],
    price: 4500000, priceLabel: "₦4,500,000/yr",
  },
  {
    id: "l18", title: "Agricultural Land — Tarauni",
    description: "Expansive 2-hectare agricultural land on the outskirts of Tarauni. Suitable for farming, greenhouse, or livestock. Access road and water borehole on site.",
    propertyType: "land", listingType: "sale", salePrice: 6_500_000,
    status: "available", category: "portfolio",
    photos: [{ id: "p32", url: U.land, alt: "Farmland" }],
    lat: 11.9600, lng: 8.5600, address: "Tarauni Farm Road, Tarauni", city: "Tarauni",
    postedBy: users[9], createdAt: "2026-06-02", sqft: 21500, price: 6500000, priceLabel: "₦6,500,000",
  },
  {
    id: "l19", title: "Townhouse — Nassarawa",
    description: "Charming 3-bedroom townhouse in a secure Nassarawa compound. Modern interior, small garden patch, dedicated parking. Quiet and family-friendly.",
    propertyType: "house", listingType: "sale", salePrice: 32_000_000,
    status: "available", category: "partnership", partnerCompany: "Alheri Properties Ltd",
    photos: [{ id: "p33", url: U.compound, alt: "Compound" }, { id: "p34", url: U.garden, alt: "Garden" }],
    lat: 11.9860, lng: 8.5150, address: "No. 6 Kofar Nassarawa Close, Nassarawa", city: "Nassarawa",
    postedBy: users[1], createdAt: "2026-06-03",
    bedrooms: 3, bathrooms: 2, sqft: 1600, features: ["Gated Compound", "Garden", "Parking"],
    price: 32000000, priceLabel: "₦32,000,000",
  },
  {
    id: "l20", title: "Fully Furnished 2-Bedroom — Kano Municipal",
    description: "Move-in ready 2-bedroom flat fully furnished with modern amenities. WiFi, satellite TV, fully equipped kitchen. Short-term and long-term lease available.",
    propertyType: "flat", listingType: "rent", rentTier: "full",
    annualRent: 1_950_000, damageDeposit: 200_000, maintenanceCharge: 100_000,
    status: "available", category: "portfolio",
    photos: [{ id: "p35", url: U.bedroom, alt: "Bedroom" }, { id: "p36", url: U.kitchen, alt: "Kitchen" }, { id: "p37", url: U.living, alt: "Living room" }],
    lat: 12.0100, lng: 8.5280, address: "No. 10 Hausa Road, Kano Municipal", city: "Kano Municipal",
    postedBy: users[2], assignedAgent: users[8], createdAt: "2026-06-04",
    bedrooms: 2, bathrooms: 1, sqft: 900,
    features: ["Fully Furnished", "WiFi", "Satellite TV", "Generator", "Water Tank"],
    price: 1950000, priceLabel: "₦1,950,000/yr",
  },
];

export const tasks: Task[] = [
  { id: "t1", title: "Find 3-bedroom house in Kano Municipal", description: "Client looking for a 3-bedroom house for rent in Kano Municipal. Budget up to ₦1.5M/year. Preferably with generator and borehole.", propertyType: "house", area: "Kano Municipal", budget: 1_500_000, deadline: "2026-06-15", notes: "Client prefers quiet neighborhood. Children in the family.", createdBy: users[2], assignedTo: users[4], status: "in_progress", source: "internal", comments: [{ id: "tc1", author: users[4], text: "Checked 3 houses. One promising on Ibrahim Taiwo Road.", createdAt: "2026-05-26" }, { id: "tc2", author: users[2], text: "Good. Send photos and I'll share with client.", createdAt: "2026-05-27" }], createdAt: "2026-05-20" },
  { id: "t2", title: "Land plot for client in Tarauni", description: "Client wants to buy land in Tarauni for residential construction. Needs C of O. Budget ₦5M - ₦7M.", propertyType: "land", area: "Tarauni", budget: 7_000_000, deadline: "2026-06-30", notes: "Client wants to build a 4-bedroom house.", createdBy: users[2], assignedTo: users[5], status: "open", source: "client_request", comments: [], createdAt: "2026-05-25" },
  { id: "t3", title: "Commercial space in Fagge for new restaurant", description: "Looking for ground floor commercial space with kitchen hookup in Fagge. High foot traffic area preferred.", propertyType: "commercial", area: "Fagge", budget: 2_000_000, deadline: "2026-06-10", notes: "Minimum 200sqm. Close to major road.", createdBy: users[1], assignedTo: users[7], status: "open", source: "internal", comments: [], createdAt: "2026-05-28" },
  { id: "t4", title: "1-bedroom flat near BUK for student", description: "Student at Bayero University needs a 1-bedroom flat within walking distance of main campus. Budget ₦300K-₦400K/year.", propertyType: "flat", area: "Tarauni", budget: 400_000, deadline: "2026-06-05", notes: "Must be close to BUK gate.", createdBy: users[3], assignedTo: users[7], status: "fulfilled", source: "client_request", submittedListingId: "l9", comments: [{ id: "tc3", author: users[7], text: "Found a good option on BUK Road.", createdAt: "2026-05-29" }], createdAt: "2026-05-22" },
  { id: "t5", title: "Luxury villa search for VIP client", description: "Corporate client relocating to Kano needs a luxury 4-5 bedroom villa in Nassarawa GRA. Budget up to ₦6M/yr. Must have pool and staff quarters.", propertyType: "house", area: "Nassarawa", budget: 6_000_000, deadline: "2026-07-01", notes: "Very important client. Premium finish.", createdBy: users[1], assignedTo: users[6], status: "in_progress", source: "internal", comments: [{ id: "tc4", author: users[6], text: "The villa at #8 GRA Road is available. Requesting a viewing.", createdAt: "2026-05-27" }], createdAt: "2026-05-24" },
  { id: "t6", title: "Retail shop for fashion boutique", description: "Female entrepreneur needs a retail shop on Ibrahim Taiwo Road for a fashion boutique. Budget ₦1M-₦1.5M/year.", propertyType: "commercial", area: "Kano Municipal", budget: 1_500_000, deadline: "2026-06-20", notes: "Needs display windows and storage room.", createdBy: users[2], assignedTo: users[8], status: "open", source: "client_request", comments: [], createdAt: "2026-05-30" },
  { id: "t7", title: "Penthouse for expat executive", description: "International NGO executive needs a luxury penthouse or high-end 3-bedroom flat in Kano Municipal. Budget ₦3.5M-₦5M/yr.", propertyType: "flat", area: "Kano Municipal", budget: 5_000_000, deadline: "2026-06-25", notes: "Must have reliable power, internet, and be in a secure building.", createdBy: users[0], assignedTo: users[4], status: "open", source: "internal", comments: [], createdAt: "2026-06-01" },
  { id: "t8", title: "Warehouse for logistics company", description: "Logistics company needs 3000+ sqft warehouse in Fagge industrial area. Must have truck access and 24hr security.", propertyType: "commercial", area: "Fagge", budget: 3_000_000, deadline: "2026-06-28", notes: "Loading bay required.", createdBy: users[1], assignedTo: users[6], status: "open", source: "client_request", comments: [], createdAt: "2026-06-02" },
  { id: "t9", title: "House for family of 6", description: "Large family needs a 4+ bedroom house in Nassarawa. Budget ₦2M-₦3M/yr. Must have borehole and be in a quiet area with good school access.", propertyType: "house", area: "Nassarawa", budget: 3_000_000, deadline: "2026-07-05", notes: "Children aged 4-14, need proximity to primary and secondary schools.", createdBy: users[9], assignedTo: users[10], status: "open", source: "client_request", comments: [], createdAt: "2026-06-03" },
  { id: "t10", title: "Land for school construction", description: "Investor wants to buy land in Tarauni for building a private primary school. Minimum 1000sqm. Budget up to ₦20M.", propertyType: "land", area: "Tarauni", budget: 20_000_000, deadline: "2026-07-15", notes: "Must have C of O and be in a residential zone.", createdBy: users[2], assignedTo: users[5], status: "open", source: "internal", comments: [], createdAt: "2026-06-04" },
];

export const commissions: Commission[] = [
  { id: "cm1", dealId: "d1", dealTitle: "Warehouse Space — Fagge", dealType: "Rent (Full Package)", totalAmount: 2_400_000, ambassadorRate: 0.08, ambassadorCut: 192_000, agentRate: 0.05, agentCut: 120_000, companyCut: 2_088_000, ambassador: users[3], agent: users[6], paidAt: "2026-04-20" },
  { id: "cm2", dealId: "d2", dealTitle: "3-Bedroom Flat — Kano Municipal", dealType: "Rent (Standard)", totalAmount: 1_200_000, ambassadorRate: 0.05, ambassadorCut: 60_000, agentRate: 0.03, agentCut: 36_000, companyCut: 1_104_000, ambassador: users[2], agent: users[4], paidAt: "2026-05-10" },
  { id: "cm3", dealId: "d3", dealTitle: "Land Plot — Tarauni", dealType: "Sale", totalAmount: 8_500_000, ambassadorRate: 0.035, ambassadorCut: 297_500, agentRate: 0.025, agentCut: 212_500, companyCut: 7_990_000, ambassador: users[2], agent: users[5], paidAt: "2026-05-22" },
  { id: "cm4", dealId: "d4", dealTitle: "Commercial Plaza — Fagge", dealType: "Rent (Partnership)", totalAmount: 3_500_000, ambassadorRate: 0.08, ambassadorCut: 280_000, agentRate: 0.05, agentCut: 175_000, companyCut: 3_045_000, ambassador: users[3], agent: users[7], paidAt: "2026-05-28" },
];

export const inquiries: Inquiry[] = [
  { id: "iq1", listingId: "l1", listingTitle: "4-Bedroom Duplex — Kano Municipal", clientName: "Dr. Amina Yusuf", clientContact: "0803 123 4567", message: "Is this still available? I am relocating from Abuja. Would like to schedule a viewing this weekend.", assignedAgent: users[4], status: "new", createdAt: "2026-05-28" },
  { id: "iq2", listingId: "l5", listingTitle: "Luxury 5-Bedroom Villa — Nassarawa", clientName: "Alh. Kabir Danjuma", clientContact: "0805 987 6543", message: "Interested in this property. Please send more photos and details about the maintenance package.", assignedAgent: users[6], status: "read", createdAt: "2026-05-26" },
  { id: "iq3", listingId: "l13", listingTitle: "6-Bedroom Mansion — Nassarawa", clientName: "Mr. John Okonkwo", clientContact: "0802 345 6789", message: "I represent an oil & gas executive being relocated to Kano. This mansion looks suitable. Can we arrange a tour this week?", assignedAgent: users[6], status: "new", createdAt: "2026-06-01" },
  { id: "iq4", listingId: "l11", listingTitle: "Modern 3-Bedroom Apartment — Kano Municipal", clientName: "Barr. Safiya Ibrahim", clientContact: "0706 543 2109", message: "I am interested in the 3-bedroom apartment on Bompai Road. Is it still available? What are the move-in requirements?", assignedAgent: users[10], status: "new", createdAt: "2026-06-02" },
  { id: "iq5", listingId: "l17", listingTitle: "Penthouse Apartment — Kano Municipal", clientName: "Engr. Tunde Balogun", clientContact: "0809 876 5432", message: "I would like to schedule a viewing of the penthouse this Saturday. Please call me to confirm availability.", assignedAgent: users[4], status: "responded", createdAt: "2026-05-30" },
];

export const reservations: Reservation[] = [
  { id: "r1", listingId: "l6", listingTitle: "2-Bedroom Self-Contain — Kano Municipal", clientName: "Malam Nura Isah", holdingDeposit: 50_000, status: "pending", expiresAt: "2026-05-31", createdAt: "2026-05-28" },
  { id: "r2", listingId: "l15", listingTitle: "Shop Space — Kano Municipal", clientName: "Hajiya Zainab Musa", holdingDeposit: 100_000, status: "confirmed", expiresAt: "2026-06-15", createdAt: "2026-06-01" },
  { id: "r3", listingId: "l20", listingTitle: "Fully Furnished 2-Bedroom — Kano Municipal", clientName: "Mr. Chinedu Okafor", holdingDeposit: 80_000, status: "pending", expiresAt: "2026-06-20", createdAt: "2026-06-04" },
];

export const customOrders: CustomOrder[] = [
  { id: "co1", propertyType: "house", area: "Nassarawa", budget: 3_000_000, notes: "Looking for a 4-bedroom house. Must have borehole and gated compound.", clientName: "Hajiya Hauwa Sani", clientContact: "0701 234 5678", status: "routed", createdAt: "2026-05-27" },
  { id: "co2", propertyType: "commercial", area: "Kano Municipal", budget: 5_000_000, notes: "Need a bank hall or large commercial space on a major road. Minimum 300sqm.", clientName: "Alh. Mukhtar Garba", clientContact: "0806 543 2109", status: "pending", createdAt: "2026-06-02" },
  { id: "co3", propertyType: "flat", area: "Tarauni", budget: 600_000, notes: "Looking for a 2-bedroom flat near BUK for visiting lecturers. Must be furnished.", clientName: "Dr. Sarah Akpan", clientContact: "0903 789 0123", status: "routed", createdAt: "2026-06-03" },
];

export const platformStats = {
  totalUsers: 11,
  totalListings: 20,
  availableListings: 17,
  reservedListings: 1,
  takenListings: 1,
  pendingWithdrawals: 2,
  totalTasks: 10,
  openTasks: 6,
  inProgressTasks: 2,
  fulfilledTasks: 2,
  totalCommissionsPaid: 1_373_500,
  totalRevenue: 14_227_000,
  totalWithdrawalsPending: 520_000,
};

export const withdrawals = [
  { id: "w1", userId: "u4", userName: "Fatima Usman", amount: 80_000, bankName: "GTBank", accountNumber: "0123456789", status: "pending" as const, requestedAt: "2026-06-02" },
  { id: "w2", userId: "u9", userName: "Maryam Yusuf", amount: 200_000, bankName: "Access Bank", accountNumber: "0987654321", status: "pending" as const, requestedAt: "2026-06-03" },
];

export const transactions = [
  { id: "tx1", userId: "u4", type: "commission_payout", amount: 120_000, reference: "CM-2026-002", method: "wallet", status: "completed", createdAt: "2026-05-10" },
  { id: "tx2", userId: "u4", type: "top_up", amount: 50_000, reference: "TU-2026-001", method: "card", status: "completed", createdAt: "2026-05-12" },
  { id: "tx3", userId: "u4", type: "payment", amount: 600_000, reference: "RNT-2026-001", method: "wallet", status: "completed", createdAt: "2026-05-15" },
  { id: "tx4", userId: "u4", type: "withdrawal", amount: 80_000, reference: "WD-2026-001", method: "transfer", status: "pending", createdAt: "2026-06-02" },
  { id: "tx5", userId: "u4", type: "commission_payout", amount: 36_000, reference: "CM-2026-003", method: "wallet", status: "completed", createdAt: "2026-05-22" },
  { id: "tx6", userId: "u5", type: "commission_payout", amount: 212_500, reference: "CM-2026-003", method: "wallet", status: "completed", createdAt: "2026-05-22" },
  { id: "tx7", userId: "u5", type: "top_up", amount: 100_000, reference: "TU-2026-002", method: "transfer", status: "completed", createdAt: "2026-05-25" },
  { id: "tx8", userId: "u6", type: "commission_payout", amount: 120_000, reference: "CM-2026-001", method: "wallet", status: "completed", createdAt: "2026-04-20" },
  { id: "tx9", userId: "u6", type: "payment", amount: 350_000, reference: "RNT-2026-002", method: "card", status: "completed", createdAt: "2026-05-01" },
  { id: "tx10", userId: "u6", type: "top_up", amount: 200_000, reference: "TU-2026-003", method: "card", status: "completed", createdAt: "2026-05-28" },
  { id: "tx11", userId: "u7", type: "commission_payout", amount: 175_000, reference: "CM-2026-004", method: "wallet", status: "completed", createdAt: "2026-05-28" },
  { id: "tx12", userId: "u8", type: "commission_payout", amount: 36_000, reference: "CM-2026-002", method: "wallet", status: "completed", createdAt: "2026-05-10" },
  { id: "tx13", userId: "u8", type: "top_up", amount: 20_000, reference: "TU-2026-004", method: "card", status: "failed", createdAt: "2026-06-01" },
  { id: "tx14", userId: "u9", type: "withdrawal", amount: 200_000, reference: "WD-2026-002", method: "transfer", status: "pending", createdAt: "2026-06-03" },
  { id: "tx15", userId: "u10", type: "commission_payout", amount: 0, reference: "CM-2026-005", method: "wallet", status: "pending", createdAt: "2026-06-05" },
];

export const auditLogs = [
  { id: "a1", action: "User Created", user: users[0], target: users[9].name, details: "Created ambassador account for Tarauni", createdAt: "2026-05-20" },
  { id: "a2", action: "Listing Approved", user: users[1], target: "4-Bedroom Duplex — Kano Municipal", details: "Approved listing for publication", createdAt: "2026-05-15" },
  { id: "a3", action: "Commission Rate Changed", user: users[1], target: "Partnership", details: "Rate changed from 12% to 15%", createdAt: "2026-05-10" },
  { id: "a4", action: "Withdrawal Approved", user: users[0], target: "Musa Ibrahim", details: "₦50,000 withdrawal approved", createdAt: "2026-05-28" },
  { id: "a5", action: "Task Assigned", user: users[2], target: "Find 3-bedroom house", details: "Assigned to Fatima Usman", createdAt: "2026-05-20" },
  { id: "a6", action: "Payment Received", user: users[1], target: "Warehouse Space — Fagge", details: "₦2,400,000 rent payment processed", createdAt: "2026-04-20" },
];
