module.exports = {
  apps: [
    {
      name: "mbpp-api",
      script: "dist/index.js",
      cwd: "/var/www/mbpp/backend",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        PORT: 4000,
      },
      error_file: "/var/www/mbpp/logs/api-error.log",
      out_file: "/var/www/mbpp/logs/api-out.log",
      merge_logs: true,
      max_memory_restart: "400M",
      autorestart: true,
      watch: false,
      restart_delay: 3000,
    },
    {
      name: "mbpp-frontend",
      script: "node_modules/next/dist/bin/next",
      args: "start -p 3000 -H 127.0.0.1",
      cwd: "/var/www/mbpp",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        PORT: 3000,
      },
      error_file: "/var/www/mbpp/logs/frontend-error.log",
      out_file: "/var/www/mbpp/logs/frontend-out.log",
      merge_logs: true,
      max_memory_restart: "800M",
      autorestart: true,
      watch: false,
      restart_delay: 3000,
    },
    {
      name: "mbpp-bot",
      script: "dist/index.js",
      cwd: "/var/www/mbpp/bot",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
      },
      error_file: "/var/www/mbpp/logs/bot-error.log",
      out_file: "/var/www/mbpp/logs/bot-out.log",
      merge_logs: true,
      max_memory_restart: "256M",
      autorestart: true,
      watch: false,
      restart_delay: 5000,
    },
  ],
};
